### ISSUE TITLE
visual diff is broken 

### ISSUE THREAD

**Issue by maboelsoudd2l** [BrightspaceUI/navigation#90]
running visual diff in an unrelated repo gets me this error:
```
  1) d2l-navigation-band
       base:
     Error: Error: failed to find element matching selector "#base"
      at ElementHandle.$eval (node_modules/puppeteer/lib/JSHandle.js:477:13)
      at processTicksAndRejections (internal/process/task_queues.js:86:5)
    -- ASYNC --
      at ElementHandle.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at DOMWorld.$eval (node_modules/puppeteer/lib/DOMWorld.js:156:21)
      at processTicksAndRejections (internal/process/task_queues.js:86:5)
    -- ASYNC --
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at Page.$eval (node_modules/puppeteer/lib/Page.js:347:29)
      at Page.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
      at VisualDiff.getRect (node_modules/@brightspace-ui/visual-diff/visual-diff.js:86:15)
      at Context.<anonymous> (node_modules/d2l-navigation/test/visual-diff/d2l-navigation-band.visual-diff.js:29:34)
      at processImmediate (internal/timers.js:443:21)
      at process.topLevelDomainCallback (domain.js:136:23)


```
I also don't like the fact that visual diff in a different repo fails because of this.

**Comment by ctwomey1** [comment]
Hey @maboelsoudd2l it looks like you might have an improper glob match.  Perhaps your visual diff is matching on a test that is inside the node modules directory.  notice the path: ```node_modules/d2l-navigation/test/visual-diff/d2l-navigation-band.visual-diff.js```

**Comment by maboelsoudd2l** [comment]
@DiljotSG why does npm import visual diff tests in the first place tho? I don't need them in my `node_modules` whenever I import this repo. Can we find a way to ommit them?

**Comment by DiljotSG** [comment]
@dlockhart

**Comment by dlockhart** [comment]
If things are actually published to NPM (like core), then yes you can omit unimportant things (and we do). But when we use GitHub references to pull in dependencies, if something's checked into source control then it's going to end up in `node_modules`.

Having said that, hopefully we can fix visual diff so that it only looks in the current project for tests, and doesn't go into `node_modules` at all.

**Comment by DiljotSG** [comment]
@dlockhart There is a PR on the activities repo that seems to be a (temporary) fix for now. https://github.com/BrightspaceHypermediaComponents/activities/pull/463

**Comment by maboelsoudd2l** [comment]
@DiljotSG its not a fix, the fact that navigation visual diff is failing is independent from https://github.com/BrightspaceHypermediaComponents/activities/pull/463

the PR in activities just omits the test.

We should probably figure out why it fails to find "#base"

**Comment by dbatiste** [comment]
Note: it's just mocha and the repo's script defines the pattern to look for...
```
"test:diff": "mocha ./test/**/*.visual-diff.js -t 40000",
```
Mocha supports a number of other filtering options to limit the scope of what tests run.  One such option is `-g` which I use sometimes use. (the `--` to pass args through to the script)... 
```
npm run test:diff -- -g some-pattern-in-describe-or-it-name
```
So, I don't _think_ any change should be needed to `visual-diff` to avoid `node_modules`.

**Comment by maboelsoudd2l** [comment]
@dbatiste I understand, with this fix in https://github.com/BrightspaceHypermediaComponents/activities/pull/463, we won't have to worry about visual diff bothering us.
 
That being said, there seems to be a problem finding this `"#base"` selector that we should look into if we want navigation visual diffs to work.

**Comment by dbatiste** [comment]
This will require some more digging.  I am unable to start the server that visual-diff uses due to a missing dependency for `mout/lang`.  This is something that gets installed in `core`, but not in this project for some reason.

**Comment by dbatiste** [comment]
@maboelsoudd2l - once I installed `mout@1.1.0` I was able to get past the issue I mentioned above, and I am able to successfully run the golden and test that uses the `#base` selector.

**Comment by svanherk** [comment]
I'm going to close this... visual-diff tests are passing in this repo, and the new visual-diff action's default path excludes `node_modules`.
